# Generated by Django 4.2.2 on 2023-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-image.jpeg', null=True, upload_to='images/'),
        ),
    ]
